language: r 
before_script:
- Rscript -e "library(acs); api.key.install('f8b2a6df01479981aef39577b3c4466f5a4c8274')"
notifications:
  email:
    recipients:
      - arilamstein@gmail.com
    on_success: change
    on_failure: change
env:
  global:
    secure: dJg3yqT+n5oTkRM1PzPhLy2cPzbKG/LPMvqdpNER298KzivMHnMjTOPz2NTc+TfeCfB6s0UROeaqMoCl6OkVqS6zXhnQkisdkJP8SsYZ+Pf5GTExSyeE3NEX/SNmjD+c9wufv8Un9T3CYzVh68VK4Ql5/VXAeTAIP2GqWOBLciY=
